# without augmentaion using modified weights for canopy
AUTO_RESUME: False
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
GPUS: (0, 1)
OUTPUT_DIR: /home/zlin/PIDNet/output/  # for log and *.pt
WORKERS: 64
PRINT_FREQ: 100

DATASET:
  DATASET: 20230916_batches1_8_freiburg_linlin
  ROOT: /home/zlin/PIDNet/mavis/20230916_batches1_8_freiburg_linlin
  # /home/zlin/PIDNet/mavis/the_ultimate_test_images # /home/zlin/PIDNet/mavis/20230323_batches1_8_linlin  # 20230318_batches1_7_cityscapes
  TRAIN_SET: train.txt
  VALID_SET: valid.txt
  TEST_SET: valid_t.txt
  NONQUALIFIED_SET: temp.txt
  NUM_CLASSES: 11

MODEL:
  NAME: 20230916_pidnet_l_trial4
  SIZE: large
  NUM_OUTPUTS: 2
  PRETRAINED: /home/zlin/PIDNet/pretrained_models/cityscapes/PIDNet_L_Cityscapes_val.pt

LOSS:
  # NAME: focaltversky
  USE_OHEM: True
  OHEMTHRES: 0.9
  BD_LABEL_THRES: 0.4
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
  USE_FocalTverskyLoss: False
  ALFA: 0.15

TRAIN:
  IMAGE_SIZE: [1024, 1024]
  CLASS_WEIGHTS: [0.0840, 0.0790, 0.0770, 0.1245, 0.1137, 0.1210, 0.0715, 0.0848, 0.0938, 0.0748, 0.0759]
  # gt: [0.0854, 0.0892, 0.0783, 0.0844, 0.0963, 0.1025, 0.0909, 0.0862, 0.0953, 0.0950, 0.0965] 
  # [0.0863, 0.0541, 0.0791, 0.1278, 0.1167, 0.1243, 0.0735, 0.0871, 0.0963, 0.0768, 0.0780]  # added weights for batches 1_8 + fraburg
  BATCH_SIZE_PER_GPU: 8  # try more 
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME_CHECKPOINT_PATH: '/home/zlin/PIDNet/output/20230916_batches1_8_freiburg_linlin/20230916_pidnet_l_trial4/checkpoint.pth.tar' 
  OPTIMIZER: sgd
  LR: 0.015
  WD: 0.0005 # L2 regulization
  MOMENTUM: 0.9 
  NESTEROV: false
  IGNORE_LABEL: 0


VALID:
  # IMAGE_SIZE: [1920, 1080]
  IMAGE_SIZE: [1024, 1024]
  BATCH_SIZE_PER_GPU: 8
  OUTPUT_INDEX: 1


TEST:
  # IMAGE_SIZE: [1920, 1080]
  IMAGE_SIZE: [1024, 1024]
  BATCH_SIZE_PER_GPU: 4
  MODEL_FILE: '/home/zlin/PIDNet/output/20230916_batches1_8_freiburg_linlin/20230916_pidnet_l_trial4/best.pth.tar' 
  OUTPUT_INDEX: 1
