# without augmentaion using modified weights for canopy
AUTO_RESUME: False
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
GPUS: (0, 1)
OUTPUT_DIR: /home/zlin/PIDNet/output/  # for log and *.pt
WORKERS: 8 # 64
PRINT_FREQ: 100

DATASET:
  DATASET: 20230323_batches1_8_cityscapes_500 # 20230318_batches1_7_cityscapes
  ROOT: /home/zlin/PIDNet/mavis/the_ultimate_test_images # /home/zlin/PIDNet/mavis/20230323_batches1_8_cityscapes_500  # /home/zlin/PIDNet/mavis/cityscapes_500
  TRAIN_SET: train.txt
  VALID_SET: valid.txt
  TEST_SET: valid_t.txt
  NONQUALIFIED_SET: temp.txt
  NUM_CLASSES: 11

MODEL:
  NAME: 20230616_pidnet_l_linlin_2gpu
  SIZE: large
  NUM_OUTPUTS: 2
  PRETRAINED: /home/zlin/PIDNet/pretrained_models/cityscapes/PIDNet_L_Cityscapes_val.pt

LOSS:
  # NAME: focaltversky
  USE_OHEM: True
  OHEMTHRES: 0.9
  BD_LABEL_THRES: 0.4
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
  USE_FocalTverskyLoss: False

TRAIN:
  IMAGE_SIZE: [1024, 1024]
  CLASS_WEIGHTS: [0.0653, 0.1382, 0.0607, 0.0654, 0.0747, 0.0795, 0.0754, 0.0669, 0.0802, 0.1448, 0.1489]
  # [0.0644, 0.0682, 0.0599, 0.0645, 0.1474, 0.1569, 0.1488, 0.0660, 0.0791, 0.0714, 0.0735] # vine pole, vine stem, vegetation
  # [0.0653, 0.1382, 0.0607, 0.0654, 0.0747, 0.0795, 0.0754, 0.0669, 0.0802, 0.1448, 0.1489]  # obstacle, human, vehicle
  # [0.0575, 0.0486, 0.0534, 0.1151, 0.1314, 0.1399, 0.0663, 0.0588, 0.0705, 0.1274, 0.1310] # vine pole, vine stem, human, vehicle
  
  BATCH_SIZE_PER_GPU: 8  # try more 
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME_CHECKPOINT_PATH: '/home/zlin/PIDNet/output/20230323_batches1_8_cityscapes_500/20230616_pidnet_l_linlin_2gpu/checkpoint.pth.tar'
  # '/home/zlin/PIDNet/output/20230323_batches1_8_linlin/20230605_pidnet_l_linlin_4gpu/checkpoint.pth.tar'
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005 # L2 regulization
  MOMENTUM: 0.9 
  NESTEROV: false
  IGNORE_LABEL: 0


VALID:
  # IMAGE_SIZE: [1920, 1080]
  IMAGE_SIZE: [1024, 1024]
  BATCH_SIZE_PER_GPU: 8
  OUTPUT_INDEX: 1


TEST:
  # IMAGE_SIZE: [1920, 1080]
  IMAGE_SIZE: [1024, 1024]
  BATCH_SIZE_PER_GPU: 4
  MODEL_FILE: '/home/zlin/PIDNet/output/20230323_batches1_8_cityscapes_500/20230616_pidnet_l_linlin_2gpu/best.pt' # best.pt
  OUTPUT_INDEX: 1
