# without augmentaion using modified weights for canopy
AUTO_RESUME: False
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
GPUS: (0, 1)
OUTPUT_DIR: /home/zlin/PIDNet/output/  # for log and *.pt
WORKERS: 64
PRINT_FREQ: 100

DATASET:
  DATASET: 20230323_batches1_8_linlin # 20230318_batches1_7_cityscapes
  ROOT: /home/zlin/PIDNet/mavis/the_ultimate_test_images  
  # /home/zlin/PIDNet/mavis/the_ultimate_test_images # /home/zlin/PIDNet/mavis/20230323_batches1_8_linlin  # 20230318_batches1_7_cityscapes
  TRAIN_SET: train.txt
  VALID_SET: valid.txt
  TEST_SET: valid_t.txt
  NONQUALIFIED_SET: temp.txt
  NUM_CLASSES: 11

MODEL:
  NAME: 20230627_pidnet_l_linlin_4gpu
  SIZE: large
  NUM_OUTPUTS: 2
  PRETRAINED: /home/zlin/PIDNet/pretrained_models/cityscapes/PIDNet_L_Cityscapes_val.pt

LOSS:
  # NAME: focaltversky
  USE_OHEM: True
  OHEMTHRES: 0.9
  BD_LABEL_THRES: 0.4
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
  USE_FocalTverskyLoss: False
  ALFA: 0.15

TRAIN:
  IMAGE_SIZE: [1024, 1024]
  CLASS_WEIGHTS: [0.0885, 0.0739, 0.0812, 0.1049, 0.0698, 0.1062, 0.0906, 0.0893, 0.1172, 0.0984, 0.0800] # reduce obstacle, vehicle, vegetation, vinestem, add canopy
  # [0.0703, 0.0734, 0.0645, 0.0694, 0.1584, 0.0844, 0.0800, 0.0709, 0.0931, 0.1563, 0.0794] # 4, 6, -2, 
  # [0.0603, 0.0630, 0.0554, 0.0595, 0.1359, 0.1447, 0.1372, 0.0608, 0.0799, 0.0671, 0.1362] # 4, 5, 6, -1
  # [0.0698, 0.0729, 0.0641, 0.0690, 0.1574, 0.1677, 0.0795, 0.0705, 0.0925, 0.0777, 0.0789] # add vine stem and vine pole 
  # [0.0653, 0.0682, 0.0600, 0.1290, 0.1473, 0.1568, 0.0744, 0.0659, 0.0866, 0.0727, 0.0738] # add vines 
  # [0.0834, 0.0871, 0.0766, 0.0824, 0.0940, 0.1001, 0.0949, 0.0841, 0.1105, 0.0928, 0.0942]  # without any weights 
  BATCH_SIZE_PER_GPU: 8  # try more 
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME_CHECKPOINT_PATH: '/home/zlin/PIDNet/output/20230323_batches1_8_linlin/20230627_pidnet_l_linlin_4gpu/checkpoint.pth.tar'
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005 # L2 regulization
  MOMENTUM: 0.9 
  NESTEROV: false
  IGNORE_LABEL: 0


VALID:
  # IMAGE_SIZE: [1920, 1080]
  IMAGE_SIZE: [1024, 1024]
  BATCH_SIZE_PER_GPU: 8
  OUTPUT_INDEX: 1


TEST:
  # IMAGE_SIZE: [1920, 1080]
  IMAGE_SIZE: [1024, 1024]
  BATCH_SIZE_PER_GPU: 4
  MODEL_FILE: '/home/zlin/PIDNet/output/20230323_batches1_8_linlin/20230627_pidnet_l_linlin_4gpu/checkpoint.pth.tar' # best.pt
  OUTPUT_INDEX: 1
