# without augmentaion using modified weights for canopy
AUTO_RESUME: False
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
GPUS: (0, 1)
OUTPUT_DIR: /home/zlin/PIDNet/output/  # for log and *.pt
WORKERS: 64
PRINT_FREQ: 100

DATASET:
  DATASET: 20230323_batches1_8_linlin # 20230318_batches1_7_cityscapes
  ROOT: /home/zlin/PIDNet/mavis/20230323_batches1_8_linlin 
  # /home/zlin/PIDNet/mavis/the_ultimate_test_images # /home/zlin/PIDNet/mavis/20230323_batches1_8_linlin  # 20230318_batches1_7_cityscapes
  TRAIN_SET: train.txt
  VALID_SET: valid.txt
  TEST_SET: valid_t.txt
  NONQUALIFIED_SET: temp.txt
  NUM_CLASSES: 11

MODEL:
  NAME: 20230915_pidnet_l_trial3
  SIZE: large
  NUM_OUTPUTS: 2
  PRETRAINED: /home/zlin/PIDNet/pretrained_models/cityscapes/PIDNet_L_Cityscapes_val.pt

LOSS:
  # NAME: focaltversky
  USE_OHEM: True
  OHEMTHRES: 0.9
  BD_LABEL_THRES: 0.4
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
  USE_FocalTverskyLoss: False
  ALFA: 0.15

TRAIN:
  IMAGE_SIZE: [1024, 1024]
  CLASS_WEIGHTS: []
  # [0.0790, 0.0826, 0.0725, 0.0937, 0.1068, 0.1233, 0.0900, 0.0797, 0.0953, 0.0879, 0.0892]
  # [0.0781, 0.0654, 0.0717, 0.0927, 0.1233, 0.1314, 0.0890, 0.0789, 0.0943, 0.0870, 0.0883]
  # without factors (updated sky): [0.0842, 0.0881, 0.0773, 0.0832, 0.0949, 0.1011, 0.0959, 0.0850, 0.1016, 0.0937, 0.0951]
  BATCH_SIZE_PER_GPU: 8  # try more 
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME_CHECKPOINT_PATH: ''
  OPTIMIZER: sgd
  LR: 0.015
  WD: 0.0005 # L2 regulization
  MOMENTUM: 0.9 
  NESTEROV: false
  IGNORE_LABEL: 0


VALID:
  # IMAGE_SIZE: [1920, 1080]
  IMAGE_SIZE: [1024, 1024]
  BATCH_SIZE_PER_GPU: 8
  OUTPUT_INDEX: 1


TEST:
  # IMAGE_SIZE: [1920, 1080]
  IMAGE_SIZE: [1024, 1024]
  BATCH_SIZE_PER_GPU: 4
  MODEL_FILE: '/home/zlin/PIDNet/output/20230323_batches1_8_linlin/20230915_pidnet_l_trial3/best.pth.tar' # best.pt
  OUTPUT_INDEX: 1
