# without augmentaion using modified weights for canopy
AUTO_RESUME: False
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
GPUS: (1,)
OUTPUT_DIR: /home/zlin/PIDNet/output/  # for log and *.pt
WORKERS: 64
PRINT_FREQ: 100

DATASET:
  DATASET: 20230916_batches1_8_freiburg_linlin
  ROOT: /home/zlin/PIDNet/mavis/20230916_batches1_8_freiburg_linlin
  # /home/zlin/PIDNet/mavis/the_ultimate_test_images # /home/zlin/PIDNet/mavis/20230323_batches1_8_linlin  # 20230318_batches1_7_cityscapes
  TRAIN_SET: train_mavis.txt
  VALID_SET: valid.txt
  TEST_SET: valid_t.txt
  NONQUALIFIED_SET: temp.txt
  NUM_CLASSES: 11

MODEL:
  NAME: 20230920_pidnet_l_trial5_trustweights # add model structure, freiburg dataset and trust weights 
  SIZE: large
  NUM_OUTPUTS: 2
  PRETRAINED: /home/zlin/PIDNet/pretrained_models/cityscapes/PIDNet_L_Cityscapes_val.pt

LOSS:
  # NAME: focaltversky
  USE_OHEM: True
  OHEMTHRES: 0.9
  BD_LABEL_THRES: 0.4
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
  USE_FocalTverskyLoss: False
  ALFA: 0.15

TRAIN:
  IMAGE_SIZE: [1024, 1024]
  CLASS_WEIGHTS: [0.0794, 0.0830, 0.0729, 0.0784, 0.1343, 0.1430, 0.1085, 0.0801, 0.0959, 0.0707, 0.0538]
  # [0.0862, 0.0720, 0.0790, 0.1022, 0.1166, 0.1241, 0.0917, 0.0870, 0.0962, 0.0671, 0.0779]
  # gt: [0.0842, 0.0881, 0.0773, 0.0832, 0.0949, 0.1011, 0.0959, 0.0850, 0.1016, 0.0937, 0.0951]
  BATCH_SIZE_PER_GPU: 8  # try more 
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME_CHECKPOINT_PATH: '/home/zlin/PIDNet/output/20230916_batches1_8_freiburg_linlin/20230920_pidnet_l_trial5_trustweights/checkpoint.pth.tar' 
  OPTIMIZER: sgd
  LR: 0.015
  WD: 0.0005 # L2 regulization
  MOMENTUM: 0.9 
  NESTEROV: false
  IGNORE_LABEL: 0


VALID:
  # IMAGE_SIZE: [1920, 1080]
  IMAGE_SIZE: [1024, 1024]
  BATCH_SIZE_PER_GPU: 8
  OUTPUT_INDEX: 1


TEST:
  # IMAGE_SIZE: [1920, 1080]
  IMAGE_SIZE: [1024, 1024]
  BATCH_SIZE_PER_GPU: 4
  MODEL_FILE: '/home/zlin/PIDNet/output/20230916_batches1_8_freiburg_linlin/20230920_pidnet_l_trial5_trustweights/best.pt' 
  OUTPUT_INDEX: 1
